# Numpy Kütüphanesi

In [2]:
import numpy as np
sinav1=[40,80,90,100]
sinav2=[60,90,95,95]

sinav1_np=np.array(sinav1)
sinav2_np=np.array(sinav2)

ort=(sinav1_np+sinav2_np)/2
print(ort)

[50.  85.  92.5 97.5]


In [5]:
import numpy as np
# 2 boyutlu bir NumPy dizisi oluşturma
benim_dizim=np.array([[1,2,3],[4,5,6]])

print(benim_dizim)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
max_deger=np.amax(arr)
print(max_deger)

5


In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
min_deger=np.amin(arr)
print(min_deger)

1


In [12]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
min_deger=np.amin(arr)
print(min_deger)

1


In [15]:
import numpy as np
arr = np.array([[1, 6, 9, 10, 5],[2,3,4,9,10]])
max_deger=np.amax(arr,axis=1)
print(max_deger)

[ 5 10]


In [16]:
import numpy as np
arr = np.array([[1, 6, 9, 10, 5],[2,3,4,9,10]])
max_deger=np.amax(arr,axis=0)
print(max_deger)

[ 2  6  9 10 10]


In [19]:
import numpy as np
arr = np.array([[1, 6, 9, 10, 5],[2,3,4,9,10]])
max_deger=np.amax(arr,axis=1,keepdims=True)
print(max_deger)

[[10]
 [10]]


In [25]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
min_deger=np.amin(arr)
print(min_deger)

1
